<section class="mt-3 card card-body">
    <h1>Gerenciar Alunos</h1>
    <div class="mt-2 text-end">
    <a href="/alunos/gerandopdf" target="_blank" class="btn btn-outline-primary"> Gerar PDF </a>

    <a href="/alunos/novo" class="btn btn-outline-dark">Novo Aluno</a>
    </div>
    <div class="table-responsive" >
    <table class="container table table-striped table-hover mt-4 ">
        <thead class="table-dark">
        <tr>
            <th>#ID</th>
            <th>Nome</th>
            <th>Matricula</th>
            <th>CPF</th>
            <th>Email</th>
            <th>Ações</th>
        </tr>
        </thead>
    <tbody >
    <?php
        foreach ($alunos ?? [] as $aluno) {

            $id = $aluno->id;

            echo "
            <tr>
            <td><strong>{$id}</strong></td>
            <td>{$aluno->nome}</td>
            <td>{$aluno->matricula}</td>
            <td>{$aluno->cpf}</td>
            <td>{$aluno->email}</td>   
            <td> <a class='btn btn-outline-warning btn-sm' href='/alunos/editar?id={$id}' > Editar </a>
            <button type='button' class='btn btn-outline-danger btn-sm' data-bs-toggle='modal' data-bs-target='#exampleModal'> Excluir</button>           
            </td>
            </tr>";
        }
    ?>
    </tbody>
    </table>
    </div>
</section>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Excluir</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Deseja mesmo excluir esse aluno?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="button" onclick="confirmar(<?php echo $id; ?>, 'aluno')" class="btn btn-danger">Sim, exclua.</button>
      </div>
    </div>
  </div>
</div> 