<?php
    date_default_timezone_set('America/Fortaleza');
    $hoje = date('d/m/Y \à\s H:i:s');

?>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<h1 class="text-center"> Relatório de Alunos </h1>        
        <hr>
        <table  class="container table table-striped table-hover mt-4">
        <thead class="table-dark" style="border-bottom:1px solid black" >
        <tr>
            <th>#ID</th>
            <th>Nome</th>
            <th>Matricula</th>
            <th>CPF</th>
            <th>Email</th>
            <th>Status</th>
        </tr>
        </thead>
    <tbody >
    <?php
        foreach ($alunos ?? [] as $aluno) {

            $id = $aluno->id;

            if ($aluno->status == 1){
                $status = 'Ativo';
            }

            echo "
            <tr>
            <td><strong>{$id}</strong></td>
            <td>{$aluno->nome}</td>
            <td>{$aluno->matricula}</td>
            <td>{$aluno->cpf}</td>
            <td>{$aluno->email}</td> 
            <td> {$status}</td>
            "; } ?>
        </tbody>
        </table>
        <p class="text-center" > Gerado em <?php echo $hoje; ?></p>
</body>
</html>