<section class="mt-3 card card-body">
    <h1>Gerenciar Professores</h1>
    <div class="mt-2 text-end">
    <a href="/professores/gerandopdf" target="_blank" class="btn btn-outline-primary">Gerar PDF</a>

    <a href="/professores/novo" class="btn btn-outline-dark">Novo Professor</a>
    </div>
    <div class="table-responsive">
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
        <tr>
            <th>#ID</th>
            <th>Nome</th>
            <th>CPF</th>
            <th>Formação</th>
            <th> Status </th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($professores ?? [] as $prof) {

            $id = $prof->id;

            if ($prof->status == 1 ){
                $status = 'Ativo';
            }else {
                $status = 'Desativado';
            }

            echo "
            <tr>
            <td><strong>{$id}</strong></td>
            <td>{$prof->nome}</td>
            <td>{$prof->cpf}</td>
            <td>{$prof->formacao}</td>
            <td>{$status} </td>   
            <td> 
            <a class='btn btn-outline-warning btn-sm' href='/professores/editar?id={$id}'> Editar </a>
            <button type='button' class='btn btn-outline-danger btn-sm' data-bs-toggle='modal' data-bs-target='#exampleModal'> Excluir</button>
            </td>
            </tr>";
        }
    ?>
    </tbody>

    </table>
    </div>
</section>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Excluir</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Deseja mesmo excluir esse professor?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="button" onclick="confirmar(<?php echo $id; ?>, 'professor')" class="btn btn-danger">Sim, exclua.</button>
      </div>
    </div>
  </div>
</div> 