<section class="mt-3 card card-body">
    <h1> Cadastrar novo professor </h1>
    <div class="row">
       <div class="col">
       </div>
        <div class="col">
         <form action="" method="POST" >
            <label for="nome"> Nome : </label>
            <input name="nome" type="text" id="nome" class="form-control mb-3">
            <label for="cpf" > CPF : </label>
            <input name="cpf" type="text" id="cpf" class="form-control mb-3">
            <label for="formacao"> Formacao :</label>
            <input name="formacao" type="text" id="formacao" class="form-control mb-3"> 
            <label for="endereco"> Endereço :</label>
            <input name="endereco" type="text" id="endereco" class="form-control mb-3"> 
            <button  type="submit"  class="btn btn-primary"> Enviar</button>
         </form>
        </div>
    </div>
</section>