<footer class="text-center">
    <h6> © Todos os direitos reservados</h6>
</footer>
<script>
function confirmar(id, onde){ 

    if (onde === "aluno"){
     location.href = '/alunos/excluir?id='+ id;
    }
    if (onde === "professor"){
        location.href = '/professores/excluir?id=' + id;
    }
    if (onde === "curso"){
        location.href = '/cursos/excluir?id=' + id;
    }
    if (onde === "categoria"){
        location.href = '/categorias/excluir?id=' + id;
    }
}
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>