
<section class="mt-3 card card-body">
    <h1>Gerenciar Cursos</h1>

    <div class="mt-2 text-end">
        <a href="/cursos/gerandopdf" class="btn btn-outline-primary">Gerar PDF</a>

        <a href="/cursos/novo" class="btn btn-outline-dark">Novo Curso</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                    foreach ($cursos ?? [] as $curso) {
                       $id = $curso['curso_id'];
                        echo "
                            <tr>
                                <td>{$id}</td>
                                <td>{$curso['curso_nome']}</td>
                                <td>{$curso['categoria_nome']}</td>
                                <td>
                                    <a href='/cursos/editar?id={$id}' class='btn btn-outline-warning'>Editar</a>
                                    <button type='button' class='btn btn-outline-danger btn-sm' data-bs-toggle='modal' data-bs-target='#exampleModal'> Excluir</button>
                                    </td>
                            </tr>
                        ";
                    }
            ?>
        </tbody>
    </table>
</section>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Excluir</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Deseja mesmo excluir esse curso?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="button" onclick="confirmar(<?php echo $id; ?>, 'curso')" class="btn btn-danger">Sim, exclua.</button>
      </div>
    </div>
  </div>
</div> 